services:

        # Product
        kek_shop_product_admin:
            class: Kek\ShopBundle\Admin\ProductAdmin
            arguments: [ @kek_shop.product_manager ]
            parent: msi_admin.admin
            tags:
                - { name: msi.admin }

        kek_shop.product_manager:
            class: %msi_admin.manager.class%
            arguments: [ %kek_shop.product.class% ]
            parent: msi_admin.manager
