services:
    # Product
    kek_shop_product_admin:
        class: %kek_shop.product_admin.class%
        arguments: [ @kek_shop.product_manager ]
        parent: msi_admin.admin
        tags:
            - { name: msi.admin }

    kek_shop.product_manager:
        class: %msi_admin.manager.class%
        arguments: [ %kek_shop.product.class% ]
        parent: msi_admin.manager

    # ProductCategory
    kek_shop_product_category_admin:
        class: %kek_shop.product_category_admin.class%
        arguments: [ @kek_shop.product_category_manager ]
        parent: msi_admin.admin
        tags:
            - { name: msi.admin }

    kek_shop.product_category_manager:
        class: %msi_admin.manager.class%
        arguments: [ %kek_shop.product_category.class% ]
        parent: msi_admin.manager

    # Order
    kek_shop_order_admin:
        class: Kek\ShopBundle\Admin\OrderAdmin
        arguments: [ @kek_shop.order_manager ]
        parent: msi_admin.admin
        tags:
            - { name: msi.admin }

    kek_shop.order_manager:
        class: %msi_admin.manager.class%
        arguments: [ %kek_shop.order.class% ]
        parent: msi_admin.manager

    # Tax
    kek_shop_tax_admin:
        class: Kek\ShopBundle\Admin\TaxAdmin
        arguments: [ @kek_shop.tax_manager ]
        parent: msi_admin.admin
        tags:
            - { name: msi.admin }

    kek_shop.tax_manager:
        class: %msi_admin.manager.class%
        arguments: [ Kek\ShopBundle\Entity\Tax ]
        parent: msi_admin.manager

    # AddressType
    kek_shop_address_type_admin:
        class: Kek\ShopBundle\Admin\AddressTypeAdmin
        arguments: [ @kek_shop.address_type_manager ]
        parent: msi_admin.admin
        tags:
            - { name: msi.admin }

    kek_shop.address_type_manager:
        class: %msi_admin.manager.class%
        arguments: [ Kek\ShopBundle\Entity\AddressType ]
        parent: msi_admin.manager

    # Address
    kek_shop_address_admin:
        class: Kek\ShopBundle\Admin\AddressAdmin
        arguments: [ @kek_shop.address_manager ]
        parent: msi_admin.admin
        tags:
            - { name: msi.admin }

    kek_shop.address_manager:
        class: %msi_admin.manager.class%
        arguments: [ %kek_shop.address.class% ]
        parent: msi_admin.manager
